AWSTemplateFormatVersion: "2010-09-09"
Description: synth easy stack

Parameters:
  DeploymentBucketName:
    Type: String  
  ContentRepoBucketName:
    Type: String  
  TextExtractorLambdaZipFile:
    Type: String
  AudioGeneratorLambdaZipFile:
    Type: String
  StartTaskLambdaZipFile:
    Type: String
  NotifySuccessLambdaZipFile:
    Type: String
  Environment:
    Type: String
    AllowedValues:
      - dev
      - stage
      - prod

Resources:

  WebSocketApiGateway:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./synth-easy-components/websocket-api-gateway.yml
      Parameters:
        Application: synth-easy
        Environment: !Ref Environment
        OnStartTaskLambdaFunctionArn: !GetAtt StartTaskLambda.Outputs.LambdaFunctionArn

  TextExctractorLambda:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./synth-easy-components/text-extractor-lambda.yml
      Parameters:
        Application: synth-easy
        Environment: !Ref Environment
        LambdaName: text-extractor
        LambdaHandler: index.handler
        LambdaBucketName: !Ref DeploymentBucketName
        LambdaZipFile: !Ref TextExtractorLambdaZipFile
        ContentRepoBucketName: !Ref ContentRepoBucketName

  GenerateAudioLambda:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./synth-easy-components/generate-audio-lambda.yml
      Parameters:
        Application: synth-easy
        Environment: !Ref Environment
        LambdaName: audio-generator
        LambdaHandler: index.handler
        LambdaBucketName: !Ref DeploymentBucketName
        LambdaZipFile: !Ref AudioGeneratorLambdaZipFile
        ContentRepoBucketName: !Ref ContentRepoBucketName

  NotifySuccessLambda:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./synth-easy-components/notify-success-lambda.yml
      Parameters:
        Application: synth-easy
        Environment: !Ref Environment
        LambdaName: notify-success
        LambdaHandler: index.handler
        LambdaBucketName: !Ref DeploymentBucketName
        LambdaZipFile: !Ref NotifySuccessLambdaZipFile
        ContentRepoBucketName: !Ref ContentRepoBucketName
        ApiGatewayEndpoint: !GetAtt WebSocketApiGateway.Outputs.ApiGatewayEndpoint
        WebSocketApi: !GetAtt WebSocketApiGateway.Outputs.WebSocketApi

  StartTaskLambda:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./synth-easy-components/start-task-lambda.yml
      Parameters:
        Application: synth-easy
        Environment: !Ref Environment
        LambdaName: start-task
        LambdaHandler: index.handler
        LambdaBucketName: !Ref DeploymentBucketName
        LambdaZipFile: !Ref StartTaskLambdaZipFile
        StateMachineArn: !Sub arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:synth-easy-${Environment}

  SynthEasyStateMachine:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./synth-easy-components/synth-easy-stepfunction.yml
      Parameters:
        Application: synth-easy
        Environment: !Ref Environment
        ExtractTextLambdaArn: !GetAtt TextExctractorLambda.Outputs.LambdaFunctionArn
        GenerateAudioLambdaArn: !GetAtt GenerateAudioLambda.Outputs.LambdaFunctionArn
        NotifySuccessLambdaArn: !GetAtt NotifySuccessLambda.Outputs.LambdaFunctionArn

  ContentRepoBucket:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./synth-easy-components/content-repo-bucket.yml
      Parameters:
        BucketName: !Ref ContentRepoBucketName
        Environment: !Ref Environment


      
        