AWSTemplateFormatVersion: "2010-09-09"
Description: synth easy stack

Parameters:
  DeploymentBucketName:
    Type: String  
  ContentRepoBucketName:
    Type: String  
  TextExtractorLambdaZipFile:
    Type: String  

Resources:

  ContentRepoBucket:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./text-extractor-lambda.yml
      Parameters:
        Application: synth-easy
        Environment: dev
        LambdaName: text-extractor
        LambdaHandler: index.handler
        LambdaBucketName: !Ref DeploymentBucketName
        LambdaZipFile: !Ref TextExtractorLambdaZipFile
        ContentRepoBucketName: !Ref ContentRepoBucketName

  TextExctractorLambda:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./content-repo-bucket.yml
      Parameters:
        BucketName: !Ref ContentRepoBucketName