AWSTemplateFormatVersion: "2010-09-09"
Description: synth easy stack

Parameters:
  DeploymentBucketName:
    Type: String  
  ContentRepoBucketName:
    Type: String  
  TextExtractorLambdaZipFile:
    Type: String
  AudioGeneratorLambdaZipFile:
    Type: String
  Environment:
    Type: String
    AllowedValues:
      - dev
      - stage
      - prod

Resources:

  TextExctractorLambda:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./synth-easy-components/text-extractor-lambda.yml
      Parameters:
        Application: synth-easy
        Environment: !Ref Environment
        LambdaName: text-extractor
        LambdaHandler: index.handler
        LambdaBucketName: !Ref DeploymentBucketName
        LambdaZipFile: !Ref TextExtractorLambdaZipFile
        ContentRepoBucketName: !Ref ContentRepoBucketName

  GenerateAudioLambda:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./synth-easy-components/generate-audio-lambda.yml
      Parameters:
        Application: synth-easy
        Environment: !Ref Environment
        LambdaName: audio-generator
        LambdaHandler: index.handler
        LambdaBucketName: !Ref DeploymentBucketName
        LambdaZipFile: !Ref AudioGeneratorLambdaZipFile
        ContentRepoBucketName: !Ref ContentRepoBucketName

  SynthEasyStateMachine:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./synth-easy-components/synth-easy-stepfunction.yml
      Parameters:
        Application: synth-easy
        Environment: !Ref Environment
        ExtractTextLambdaArn: !GetAtt TextExctractorLambda.Outputs.LambdaFunctionArn
        GenerateAudioLambdaArn: !GetAtt GenerateAudioLambda.Outputs.LambdaFunctionArn

  ContentRepoBucket:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./content-repo-bucket.yml
      Parameters:
        BucketName: !Ref ContentRepoBucketName
        Environment: !Ref Environment