AWSTemplateFormatVersion: "2010-09-09"
Description: easy reader Content Bucket

Parameters:
  BucketName:
    Type: String
  Environment:
    Type: String
    AllowedValues:
      - dev
      - stage
      - prod

Resources:
  ContentBucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketName: !Ref BucketName
      CorsConfiguration:
        CorsRules:
          -
            AllowedOrigins: 
              - "*"
            AllowedMethods: 
              - GET
            AllowedHeaders: 
              - "*"

Outputs:
  ContentBucketName:
    Description: ContentBucketName Arn
    Value: !GetAtt ContentBucket.Arn
    Export:
      Name: !Sub ${AWS::StackName}-easy-reader-content-bucket-arn