AWSTemplateFormatVersion: '2010-09-09'
Description: 'easy reader Step function'

Parameters:
  Application:
    Type: String
  Environment:
    Type: String
    AllowedValues:
      - dev
      - stage
      - prod
  ExtractTextLambdaArn:
    Type: String
  GenerateAudioLambdaArn:
    Type: String
  NotifySuccessLambdaArn:
    Type: String
  HandleErrorLambdaArn:
    Type: String

Resources:
  EasyReaderStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub ${Application}-${Environment}
      StateMachineType: EXPRESS
      DefinitionString: !Sub | 
        {
          "Comment": "SynEasy State Machine",
          "StartAt": "ExtractText",
          "Version": "1.0",
          "States": {
            "ExtractText": {
              "Type": "Task",
              "Resource": "${ExtractTextLambdaArn}",
              "Next": "GenerateAudio",
              "Catch": [
                {
                  "ErrorEquals": [ "States.ALL" ],
                  "Next": "ErrorHandler",
                  "ResultPath": "$.error"
                }]
            },
            "GenerateAudio": {
              "Type": "Task",
              "Resource": "${GenerateAudioLambdaArn}",
              "Next": "NotifySuccess",
              "Catch": [
              {
                "ErrorEquals": [ "States.ALL" ],
                "Next": "ErrorHandler",
                "ResultPath": "$.error"
              }]
            },
            "NotifySuccess": {
              "Type": "Task",
              "Resource": "${NotifySuccessLambdaArn}",
              "Next": "Success",
              "Catch": [
              {
                "ErrorEquals": [ "States.ALL" ],
                "Next": "ErrorHandler",
                "ResultPath": "$.error"
              }]
            },
            "ErrorHandler": {
              "Type": "Task",
              "Resource": "${HandleErrorLambdaArn}",
              "Next": "Error"
            },
            "Error": {
              "Type": "Fail"
            },
            "Success": {
              "Type": "Succeed"
            }
          }
        }
      RoleArn: !GetAtt EasyReaderStateMachineRole.Arn


  EasyReaderStateMachineRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: !Sub states.${AWS::Region}.amazonaws.com
          Action: 'sts:AssumeRole'
      Policies:
      - PolicyName: lambda
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: lambda:InvokeFunction
            Resource:
            - !Ref ExtractTextLambdaArn
            - !Ref GenerateAudioLambdaArn
            - !Ref NotifySuccessLambdaArn
            - !Ref HandleErrorLambdaArn

Outputs:
  StateMachineArn:
    Value: !Ref EasyReaderStateMachine
