AWSTemplateFormatVersion: "2010-09-09"
Description: Front end bucket

Parameters:
  BucketName:
    Type: String
  Environment:
    Type: String
    AllowedValues:
      - dev
      - stage
      - prod

Resources:
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Ref BucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: public-read
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join ['', ['arn:aws:s3:::', !Ref FrontendBucket, /*]]
      

Outputs:
  FrontendBucketName:
    Description: FrontendBucketName Arn
    Value: !GetAtt FrontendBucket.Arn
    Export:
      Name: !Sub ${AWS::StackName}-easy-reader-frontend-bucket-arn