name: easy-reader

on:
  push:
    branches: [ main ]

      
  pull_request:
    branches: [ main ]

env:
  APPLICATION_NAME: easy-reader
  DEPLOYMENT_BUCKET_NAME: easy-reader-deployment-bucket
  WILDCARD_DOMAIN_NAME: *.easy-reader.inflow-it-labs.tk
  API_DOMAIN_NAME: api.easy-reader.inflow-it-labs.tk
  APP_DOMAIN_NAME: app.easy-reader.inflow-it-labs.tk
  TEXT_EXTRACTOR_COMPONENT_NAME: text-extractor
  AUDIO_GENERATOR_COMPONENT_NAME: audio-generator
  NOTIFY_SUCCESS_COMPONENT_NAME: notify-success
  HANDLE_ERROR_COMPONENT_NAME: handle-error
  START_TASK_COMPONENT_NAME: start-task
  CONTENT_REPO_BUCKET_NAME: easy-reader-content-repo
  FRONT_END_BUCKET_NAME: easy-reader

jobs:

  build-frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/frontend/easy-reader-front
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3.1.1
      with:
        node-version: 14

    - name: Restore dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Upload frontend build artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.APPLICATION_NAME }}-frontend
        path: src/frontend/easy-reader-front/build
    
  build-lambdas: 
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/backend

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3.1.1
      with:
        node-version: 14

    - name: Restore dependencies
      run: npm install

    - name: Build
      run: npm run bundle

    - name: Zip lambdas
      run: |
        declare -a ComponentArray=(
          ${{ env.TEXT_EXTRACTOR_COMPONENT_NAME }} 
          ${{ env.AUDIO_GENERATOR_COMPONENT_NAME }}
          ${{ env.START_TASK_COMPONENT_NAME }}
          ${{ env.NOTIFY_SUCCESS_COMPONENT_NAME }}
          ${{ env.HANDLE_ERROR_COMPONENT_NAME }}
        )

        for component in ${ComponentArray[@]}; do
          cd dist/$component
          zip -r $component-${{ github.sha }}.zip  .
          cd ../..
        done


    - name: Upload lambda build artifact
      uses: actions/upload-artifact@v3
      with:
        name: lambdas-artifact
        path: src/backend/dist/**/*.zip

  create-or-update-lambda-deployment-bucket:
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v3
      
    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Create or update deployment bucket
        run: |
          aws cloudformation deploy --template-file ./aws/cfn/deployment-bucket.yml --stack-name easy-reader-deployment-bucket --parameter-overrides DeploymentBucketName=${{ env.DEPLOYMENT_BUCKET_NAME}}

  upload-lambda-artifacts-to-s3:
    needs: [
      build-lambdas, 
      create-or-update-lambda-deployment-bucket
    ]
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v3
      with:
        name: lambdas-artifact
        path: lambdas-artifact


   
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Upload to S3
      run: |
        declare -a ComponentArray=(
          ${{ env.TEXT_EXTRACTOR_COMPONENT_NAME }} 
          ${{ env.AUDIO_GENERATOR_COMPONENT_NAME }}
          ${{ env.START_TASK_COMPONENT_NAME }}
          ${{ env.NOTIFY_SUCCESS_COMPONENT_NAME }}
          ${{ env.HANDLE_ERROR_COMPONENT_NAME }}
        )

        for component in ${ComponentArray[@]}; do
          aws s3 cp lambdas-artifact/$component/$component-${{ github.sha }}.zip s3://${{ env.DEPLOYMENT_BUCKET_NAME }}
        done


  deploy:
    needs: [upload-lambda-artifacts-to-s3, build-frontend]
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3 
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Package and Deploy Infrastructure
      run: |
        aws cloudformation package --template-file ./aws/cfn/easy-reader-stack.yml --output-template-file easy-reader-stack.packaged.yml --s3-bucket ${{ env.DEPLOYMENT_BUCKET_NAME}}
        aws cloudformation deploy --template-file easy-reader-stack.packaged.yml --stack-name easy-reader --parameter-overrides \
            Application=${{ env.APPLICATION_NAME }} \
            Environment=dev \
            DeploymentBucketName=${{ env.DEPLOYMENT_BUCKET_NAME }} \
            TextExtractorLambdaZipFile=${{ env.TEXT_EXTRACTOR_COMPONENT_NAME }}-${{ github.sha }}.zip \
            AudioGeneratorLambdaZipFile=${{ env.AUDIO_GENERATOR_COMPONENT_NAME }}-${{ github.sha }}.zip \
            StartTaskLambdaZipFile=${{ env.START_TASK_COMPONENT_NAME }}-${{ github.sha }}.zip \
            NotifySuccessLambdaZipFile=${{ env.NOTIFY_SUCCESS_COMPONENT_NAME }}-${{ github.sha }}.zip \
            HandleErrorLambdaZipFile=${{ env.HANDLE_ERROR_COMPONENT_NAME }}-${{ github.sha }}.zip \
            ContentRepoBucketName=${{ env.CONTENT_REPO_BUCKET_NAME }} \
            FrontendBucketName=${{ env.FRONT_END_BUCKET_NAME }} \
            Domain=${{ env.WILDCARD_DOMAIN_NAME }}
            ApiDomain=${{ env.API_DOMAIN_NAME }}
            AppDomain=${{ env.APP_DOMAIN_NAME }}
            HostedZoneId=${{ secrets.HOSTED_ZONE_ID }}
            --capabilities CAPABILITY_IAM
        if [[$? -ne 0]];
        then
          aws cloudformation describe-stack-events --stack-name easy-reader
        fi

    - uses: actions/download-artifact@v3
      with:
        name: ${{ env.APPLICATION_NAME }}-frontend
        path: ${{ env.APPLICATION_NAME }}-frontend

    - name: Deploy frontend
      run: |
        aws s3 cp --recursive ./${{ env.APPLICATION_NAME }}-frontend/ s3://${{ env.FRONT_END_BUCKET_NAME }}

        